global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'url-minifier'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
