name: Backend Quality

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**.go'
      - 'go.*'
      - '.golangci.yml'

jobs:
  quality:
    name: Backend Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
        
      - name: Run golangci-lint
        run: golangci-lint run ./...
        
      - name: Check formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted correctly:"
            gofmt -l .
            exit 1
          fi
          
      - name: Run Go tests
        run: go test -v ./...
