name: UI Quality

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'services/ui/**'

jobs:
  quality:
    name: UI Quality Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        working-directory: ./services/ui

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Type checking
        run: npm run typecheck || npm run type-check

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test -- --passWithNoTests

      - name: Build
        run: npm run build
